import Link from 'next/link'
import clsx from 'clsx';

import '../globals.css'
import { Inter } from 'next/font/google'
import { getPages } from '@sanity/sanity.utils';

const fontUSed = Inter({
	weight: '400',
	subsets: ['latin']
});

export const metadata = {
	title: 'My Awesome Site!',
	description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const pages = await getPages();

	return (
		<html lang="en">
			<body className={clsx("max-w-3xl mx-auto py-10")}>
				<header className='flex items-center justify-between pb-10'>
					<Link href={'/'}
						className='bg-gradient-to-r from-orange-400 to-violet-800 bg-clip-text text-transparent text-lg font-bold'
					>
						NavBar
					</Link>
					<div className='flex items-center gap-5 text-sm text-gray-600'>
						{pages.map(({ _id, title, slug}) => {
							console.log({ slug })
							return(
								<Link key={_id} href={slug} >
								{title}
							</Link>
							)
						})}
					</div>
				</header>
				<main className='py-15'>{children}</main>
				<footer></footer>
			</body>
		</html>
	)
}
